export const EARTH_SURFACE_ROTATION_SPEED = 0.08;

// Keep the clouds linked to Earth's spin, with only a small additional drift over the surface.
export const EARTH_CLOUD_RELATIVE_ROTATION_FACTOR = 0.0625;
export const EARTH_CLOUD_RELATIVE_ROTATION_SPEED =
  EARTH_SURFACE_ROTATION_SPEED * EARTH_CLOUD_RELATIVE_ROTATION_FACTOR;
export const EARTH_CLOUD_WORLD_ROTATION_SPEED =
  EARTH_SURFACE_ROTATION_SPEED + EARTH_CLOUD_RELATIVE_ROTATION_SPEED;
export const EARTH_CLOUD_UV_SPEED =
  EARTH_CLOUD_WORLD_ROTATION_SPEED / (Math.PI * 2);
export const EARTH_CLOUD_SHADOW_SHELL_RADIUS = 1.018;
